###
POST http://localhost:8080/api/order/b5647c7b-5e16-40dd-8726-48bd0ad40cab
Content-Type: application/json

{
  "total": 127.95,
  "orderedProducts": [
    {
      "name": "sunglasses",
      "quantity": 2
    }
  ]
}

###
POST http://localhost:8080/api/confirmation/b5647c7b-5e16-40dd-8726-48bd0ad40cab
Content-Type: application/json

{
  "trackingNumber": "1Z 999 AA1 01 2345 6784"
}