version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: application_db
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]