services:
  app:
    build:
      context: ..
      dockerfile: script/Dockerfile
    environment:
      MAESTRO_DB_URL: jdbc:postgresql://postgres:5432/application_db
      MAESTRO_DB_USERNAME: postgres
      MAESTRO_DB_PASSWORD: password
    ports:
      - "8080:8080"
      - "8000:8000"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: application_db
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]