name: Dependabot Auto-Run
on: push

permissions:
  contents: write
  pull-requests: write
  security-events: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Submit Dependency Snapshot
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/dependency-graph/snapshots